platform :ios, '11.0'
use_frameworks!

def example_pods
#  pod 'FirebaseAnalytics'
  pod 'FirebaseMessaging'
  pod 'OneSignalXCFramework', '>= 3.0.0', '< 4.0'
  pod 'FlareLane', :path => '../'
end

target 'FlareLane_Example' do
  example_pods

  target 'FlareLane_Tests' do
    inherit! :search_paths
  end
end

target 'FlareLaneNotificationServiceExtension' do
  example_pods
end
