platform :ios, '12.0'
use_frameworks!

def example_pods
  pod 'FirebaseMessaging'
  pod 'FlareLane', :path => '../'
end

target 'FlareLane_Example' do
  example_pods

  target 'FlareLane_Tests' do
    inherit! :search_paths
  end
end

target 'FlareLaneNotificationServiceExtension' do
  example_pods
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['APPLICATION_EXTENSION_API_ONLY'] = 'No'
    end
  end
end
